### ISSUE TITLE
Could you please update this in the new translations branch

### ISSUE THREAD

**Issue by dvdvideo1234** [Sony-dev/Offset-Hoverballs#36]
https://github.com/Sony-dev/Offset-Hoverballs/blame/1d9915a66e4d857455d70e49694e06617b472a72/resource/localization/bg/offset_hoverball.properties#L69 ( https://github.com/Sony-dev/Offset-Hoverballs/tree/translation-changes )

Old:
```
status.offset_hoverball.brake_enabled=Спирачка разрешен
```

New:
```
status.offset_hoverball.brake_enabled=Спирачка разрешена
```

**Comment by dvdvideo1234** [comment]
`Brake` in Bulgarian is feminine, but `Allowed` is masculine :D

**Comment by Sony-dev** [comment]
Updated, good catch :)
